In [2]:
import numpy as np

In [3]:
A = np.array([[1, 3],[4,9],[2,8]])
A

array([[1, 3],
       [4, 9],
       [2, 8]])

In [4]:
A.shape


(3, 2)

In [5]:
A.T

array([[1, 4, 2],
       [3, 9, 8]])

array([[ 3, 11],
       [ 6, 10],
       [ 9, 13]])

In [6]:
A.T.shape


(2, 3)

In [8]:
B = np.array ([[2,8],[2,1],[7,5]])
B

array([[2, 8],
       [2, 1],
       [7, 5]])

array([[ 2, 24],
       [ 8,  9],
       [14, 40]])